#!/bin/sh

# Canonical absolute path to the PID file.
#
# DEFAULT: /run/nginxfront.pid
#PIDFILE=/var/run/nginxfront.pid

# Arguments that should be passed to the daemon.
#
# DEFAULT: ''
#DAEMON_ARGS=''

# Override verbosity environment variable.
#
# DEFAULT: no
#VERBOSE=yes
